/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { TokenLib, TokenLibInterface } from "../../../libraries/TokenLib.sol/TokenLib.js";

  const _abi = [
  {
    "inputs": [],
    "name": "SkillNameRequired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenDoesNotExist",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenUriRequired",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220febee38c363aeb48d799bb720a544cf8b4c82c1767929f50c67379bbc8316f5e64736f6c634300081c0033";

  
      type TokenLibConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: TokenLibConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class TokenLib__factory extends ContractFactory {
    
      constructor(...args: TokenLibConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<TokenLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): TokenLib__factory {
      return super.connect(runner) as TokenLib__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): TokenLibInterface {
      return new Interface(_abi) as TokenLibInterface;
    }
    
    override attach(address: string | Addressable): TokenLib {
      return super.attach(address) as TokenLib;
    }
  static connect(address: string, runner?: ContractRunner | null): TokenLib {
      return new Contract(address, _abi, runner) as unknown as TokenLib;
    }
  }

  
  